service: FIRSTTASK
frameworkVersion: '3'



provider:
  name: aws
  runtime: nodejs18.x

functions:
  
  signUpUser:
    handler: Functions/signup.signUpFunction
    events:
      - http:
          path: /sign/up/user
          method: post  

  signInpUser:
    handler: Functions/signin.signInUser
    events:
      - httpApi:
          path: /sign/in/user
          method: post 

  updateUser:
    handler: Functions/update.updateUserDetails
    events:
      - http:
          path: /update/user
          method: post

  notesOfUser:
    handler: Functions/notes.userNotes
    events:
      - http:
          path: /insert/user/notes
          method: post    

  deleteNotesOfUser:
    handler: Functions/deletenotes.deleteUser
    events:
      - http:
          path: /delete/notes/user
          method: delete      

  numberOfNotesOfUser:
    handler: Functions/nofnotes.numberOfTextOfUser
    events:
      - http:
          path: /number/notes/user
          method: get                   

plugins:
  - serverless-offline                                    
                  


